CREATE TABLE [dbo].[NiveauxEtudes] (
    [Clé]          NVARCHAR (2)   NOT NULL,
    [Dénomination] NVARCHAR (255) NOT NULL,
    PRIMARY KEY CLUSTERED ([Clé] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

