CREATE TABLE [dbo].[Parametre] (
    [idParam]   BIGINT NOT NULL,
    [idSession] BIGINT NOT NULL,
    PRIMARY KEY CLUSTERED ([idParam] ASC, [idSession] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

