CREATE TABLE [dbo].[Statuts] (
    [Clé]          NVARCHAR (11) NOT NULL,
    [Dénomination] NVARCHAR (30) NOT NULL,
    PRIMARY KEY CLUSTERED ([Clé] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

