CREATE TABLE [dbo].[Utilisateur] (
    [idUtilisateur] INT           NOT NULL,
    [eMail]         NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([idUtilisateur] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

